/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    opportunities: Opportunity;
    submissions: Submission;
    'research-runs': ResearchRun;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    opportunities: OpportunitiesSelect<false> | OpportunitiesSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    'research-runs': ResearchRunsSelect<false> | ResearchRunsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      'refresh-opportunity-lifecycle': TaskRefreshOpportunityLifecycle;
      'research-opportunity': TaskResearchOpportunity;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opportunities".
 */
export interface Opportunity {
  id: number;
  slug: string;
  title: string;
  organizer: string;
  edition?: string | null;
  summary: string;
  details?:
    | {
        heading: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  mainCategory:
    | 'events'
    | 'internships'
    | 'competitions'
    | 'research'
    | 'fellowships'
    | 'scholarships'
    | 'courses'
    | 'innovation'
    | 'creative-calls'
    | 'exchanges'
    | 'volunteering'
    | 'other';
  category:
    | 'conference'
    | 'summit'
    | 'forum'
    | 'workshop-seminar'
    | 'networking-event'
    | 'congress'
    | 'cultural-program'
    | 'internship'
    | 'apprenticeship'
    | 'traineeship'
    | 'competition'
    | 'challenge'
    | 'hackathon'
    | 'research-program'
    | 'research-placement'
    | 'research-internship'
    | 'fellowship'
    | 'leadership-program'
    | 'scholarship'
    | 'grant'
    | 'travel-grant'
    | 'academy'
    | 'summer-school'
    | 'winter-school'
    | 'course-training'
    | 'bootcamp'
    | 'startup-program'
    | 'accelerator'
    | 'incubator'
    | 'entrepreneurship-program'
    | 'creative-call'
    | 'media-call'
    | 'writing-call'
    | 'design-call'
    | 'exchange-program'
    | 'mobility-program'
    | 'volunteering-program'
    | 'service-program'
    | 'other';
  format: 'in-person' | 'online' | 'hybrid' | 'not-confirmed';
  /**
   * Locked to explicit contributor selection. AI can warn but never alter it.
   */
  audienceGroups?:
    | (
        | 'secondary-students'
        | 'university-students'
        | 'graduate-students'
        | 'researchers'
        | 'early-career'
        | 'all-students'
      )[]
    | null;
  audienceClassificationSource: 'submitted-dropdown-only' | 'legacy-explicit';
  dates?: {
    timezone?: string | null;
    rolling?: boolean | null;
    applicationDeadlineAt?: string | null;
    applicationDeadlineDisplay?: string | null;
    applicationDeadlineRaw?: string | null;
    startAt?: string | null;
    startDisplay?: string | null;
    endAt?: string | null;
    endDisplay?: string | null;
  };
  location: {
    display: string;
    city?: string | null;
    country?: string | null;
    countryCode?: string | null;
    region?: string | null;
  };
  eligibility?: {
    summary?: string | null;
    geographicRegions?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    eligibleCountries?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    academicLevels?:
      | ('secondary-school' | 'undergraduate' | 'graduate' | 'doctoral' | 'postdoctoral' | 'early-career' | 'any')[]
      | null;
    fields?:
      | (
          | 'arts-humanities'
          | 'business-economics'
          | 'computing-ai-data'
          | 'education'
          | 'engineering-technology'
          | 'environment-sustainability'
          | 'health-life-sciences'
          | 'law-policy'
          | 'natural-sciences'
          | 'social-sciences'
          | 'multidisciplinary'
        )[]
      | null;
    majors?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    requirements?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  funding?: {
    applicationFee?: string | null;
    participationFee?: string | null;
    scholarship?: string | null;
    travelSupport?: string | null;
    accommodation?: string | null;
    meals?: string | null;
    stipendOrSalary?: string | null;
    prizes?: string | null;
    visaSupport?: string | null;
    accessibilitySupport?: string | null;
    otherSupport?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    filterLabels?:
      | (
          | 'free'
          | 'scholarship'
          | 'travel-support'
          | 'accommodation'
          | 'meals'
          | 'stipend-or-salary'
          | 'prizes'
          | 'not-confirmed'
        )[]
      | null;
  };
  officialUrl: string;
  applicationUrl?: string | null;
  activities?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  benefits?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  topics?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  sources: {
    url: string;
    label: string;
    checkedAt: string;
    supportedFields?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    reviewer?: string | null;
    id?: string | null;
  }[];
  lastVerifiedAt?: string | null;
  legacy?: {
    slug?: string | null;
    sourceIssue?: string | null;
    publicationReview?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    verificationNotes?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    importedAt?: string | null;
    archived?: boolean | null;
    rawRecord?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  moderationFlags?:
    | (
        | 'missing-application-link'
        | 'unnormalized-deadline'
        | 'missing-funding'
        | 'category-mismatch'
        | 'stale'
        | 'expired'
        | 'needs-verification'
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  sourceUrl: string;
  title: string;
  mainCategory:
    | 'not-sure'
    | 'events'
    | 'internships'
    | 'competitions'
    | 'research'
    | 'fellowships'
    | 'scholarships'
    | 'courses'
    | 'innovation'
    | 'creative-calls'
    | 'exchanges'
    | 'volunteering'
    | 'other';
  note?: string | null;
  contactEmail?: string | null;
  consentedAt: string;
  status: 'received' | 'researching' | 'draft-ready' | 'in-review' | 'approved' | 'rejected';
  requestFingerprint: string;
  contactDeleteAfter?: string | null;
  internalNotes?: string | null;
  linkedOpportunity?: (number | null) | Opportunity;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-runs".
 */
export interface ResearchRun {
  id: number;
  reference: string;
  submission: number | Submission;
  opportunity?: (number | null) | Opportunity;
  requestedBy: number | User;
  status: 'succeeded' | 'failed';
  model: string;
  modelSnapshot?: string | null;
  promptVersion: string;
  /**
   * Untrusted proposal; compare every field with citations.
   */
  proposal?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  citations?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  warnings?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  usage?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  failure?: string | null;
  startedAt: string;
  completedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'refresh-opportunity-lifecycle' | 'research-opportunity';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'refresh-opportunity-lifecycle' | 'research-opportunity') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'opportunities';
        value: number | Opportunity;
      } | null)
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null)
    | ({
        relationTo: 'research-runs';
        value: number | ResearchRun;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opportunities_select".
 */
export interface OpportunitiesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  organizer?: T;
  edition?: T;
  summary?: T;
  details?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  featured?: T;
  mainCategory?: T;
  category?: T;
  format?: T;
  audienceGroups?: T;
  audienceClassificationSource?: T;
  dates?:
    | T
    | {
        timezone?: T;
        rolling?: T;
        applicationDeadlineAt?: T;
        applicationDeadlineDisplay?: T;
        applicationDeadlineRaw?: T;
        startAt?: T;
        startDisplay?: T;
        endAt?: T;
        endDisplay?: T;
      };
  location?:
    | T
    | {
        display?: T;
        city?: T;
        country?: T;
        countryCode?: T;
        region?: T;
      };
  eligibility?:
    | T
    | {
        summary?: T;
        geographicRegions?:
          | T
          | {
              value?: T;
              id?: T;
            };
        eligibleCountries?:
          | T
          | {
              value?: T;
              id?: T;
            };
        academicLevels?: T;
        fields?: T;
        majors?:
          | T
          | {
              value?: T;
              id?: T;
            };
        requirements?:
          | T
          | {
              value?: T;
              id?: T;
            };
      };
  funding?:
    | T
    | {
        applicationFee?: T;
        participationFee?: T;
        scholarship?: T;
        travelSupport?: T;
        accommodation?: T;
        meals?: T;
        stipendOrSalary?: T;
        prizes?: T;
        visaSupport?: T;
        accessibilitySupport?: T;
        otherSupport?:
          | T
          | {
              value?: T;
              id?: T;
            };
        filterLabels?: T;
      };
  officialUrl?: T;
  applicationUrl?: T;
  activities?:
    | T
    | {
        value?: T;
        id?: T;
      };
  benefits?:
    | T
    | {
        value?: T;
        id?: T;
      };
  topics?:
    | T
    | {
        value?: T;
        id?: T;
      };
  sources?:
    | T
    | {
        url?: T;
        label?: T;
        checkedAt?: T;
        supportedFields?:
          | T
          | {
              value?: T;
              id?: T;
            };
        reviewer?: T;
        id?: T;
      };
  lastVerifiedAt?: T;
  legacy?:
    | T
    | {
        slug?: T;
        sourceIssue?: T;
        publicationReview?: T;
        verificationNotes?: T;
        importedAt?: T;
        archived?: T;
        rawRecord?: T;
      };
  moderationFlags?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  sourceUrl?: T;
  title?: T;
  mainCategory?: T;
  note?: T;
  contactEmail?: T;
  consentedAt?: T;
  status?: T;
  requestFingerprint?: T;
  contactDeleteAfter?: T;
  internalNotes?: T;
  linkedOpportunity?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-runs_select".
 */
export interface ResearchRunsSelect<T extends boolean = true> {
  reference?: T;
  submission?: T;
  opportunity?: T;
  requestedBy?: T;
  status?: T;
  model?: T;
  modelSnapshot?: T;
  promptVersion?: T;
  proposal?: T;
  citations?: T;
  warnings?: T;
  usage?: T;
  failure?: T;
  startedAt?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  featuredOpportunities?: (number | Opportunity)[] | null;
  announcement?: string | null;
  closingSoonDays: number;
  publicEmail?: string | null;
  aboutUrl?: string | null;
  privacyUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  featuredOpportunities?: T;
  announcement?: T;
  closingSoonDays?: T;
  publicEmail?: T;
  aboutUrl?: T;
  privacyUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskRefresh-opportunity-lifecycle".
 */
export interface TaskRefreshOpportunityLifecycle {
  input?: unknown;
  output: {
    reviewed: number;
    flagged: number;
    contactsDeleted: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskResearch-opportunity".
 */
export interface TaskResearchOpportunity {
  input: {
    submissionId: number;
    requestedBy: number;
  };
  output: {
    researchRunId: number;
    status: 'succeeded' | 'failed';
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}